### ISSUE TITLE
Not compatible with nixos-18.03?

### ISSUE THREAD

**Issue by qrilka** [typeable/nixpkgs-stackage#24]
I've installed this overlay but installing `stackage2nix` fails:
```
error: anonymous function at /nix/store/p3dcl2p61lbz971qi799iq62qkfydgkq-nixpkgs-18.03pre123927.5be70c39f3e/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:4:1 called with unexpected argument 'buildHaskellPackages', at /nix/store/p3dcl2p61lbz971qi799iq62qkfydgkq-nixpkgs-18.03pre123927.5be70c39f3e/nixpkgs/lib/customisation.nix:74:12
(use '--show-trace' to show detailed location information)
```
I guess it's something related to https://github.com/typeable/stackage2nix/pull/57 but at the moment unfortunately I don't understand the internals good enough

**Comment by 4e6** [comment]
Please provide some details on how to reproduce this problem

**Comment by qrilka** [comment]
Sorry, probably there was something with about my Nix overlays, it did built later
